"""Pydantic schemas."""

from app.schemas.auth import Token, TokenData, UserCreate, UserLogin, UserResponse
from app.schemas.vendor import (
    VendorCreate,
    VendorUpdate,
    VendorResponse,
    VendorUserCreate,
    VendorUserUpdate,
    VendorUserResponse,
    VendorUserListResponse,
    VendorWithUsersResponse,
)
from app.schemas.customer import (
    CustomerCreate,
    CustomerUpdate,
    CustomerResponse,
    CustomerListResponse,
    LicenseUsageResponse,
    LicenseUsageCreate,
    LicenseHistoryResponse,
    LicenseAdjustRequest,
    LicenseAlertResponse,
    LicenseAlertAcknowledge,
    CustomerWithLicensesResponse,
)
from app.schemas.module import (
    ModuleCreate,
    ModuleUpdate,
    ModuleResponse,
    ModuleListResponse,
    ModuleDeploymentCreate,
    ModuleDeploymentResponse,
    ModuleDeploymentListResponse,
    ReleaseNoteCreate,
    ReleaseNoteResponse,
    ReleaseNoteListResponse,
    ModuleWithDeploymentsResponse,
)
from app.schemas.history import (
    EventType,
    FeedbackType,
    ModuleEventCreate,
    ModuleEventResponse,
    ModuleEventListResponse,
    LLMConversationCreate,
    LLMConversationUpdate,
    LLMConversationResponse,
    LLMConversationListResponse,
    LLMMessageCreate,
    LLMMessageResponse,
    LLMMessageListResponse,
    LLMFeedbackCreate,
    LLMFeedbackResponse,
    LLMFeedbackListResponse,
    LLMConversationWithMessagesResponse,
    ContextRequest,
    ContextResponse,
)

__all__ = [
    # Auth
    "Token",
    "TokenData",
    "UserCreate",
    "UserLogin",
    "UserResponse",
    # Vendor
    "VendorCreate",
    "VendorUpdate",
    "VendorResponse",
    "VendorUserCreate",
    "VendorUserUpdate",
    "VendorUserResponse",
    "VendorUserListResponse",
    "VendorWithUsersResponse",
    # Customer
    "CustomerCreate",
    "CustomerUpdate",
    "CustomerResponse",
    "CustomerListResponse",
    "LicenseUsageResponse",
    "LicenseUsageCreate",
    "LicenseHistoryResponse",
    "LicenseAdjustRequest",
    "LicenseAlertResponse",
    "LicenseAlertAcknowledge",
    "CustomerWithLicensesResponse",
    # Module
    "ModuleCreate",
    "ModuleUpdate",
    "ModuleResponse",
    "ModuleListResponse",
    "ModuleDeploymentCreate",
    "ModuleDeploymentResponse",
    "ModuleDeploymentListResponse",
    "ReleaseNoteCreate",
    "ReleaseNoteResponse",
    "ReleaseNoteListResponse",
    "ModuleWithDeploymentsResponse",
    # History
    "EventType",
    "FeedbackType",
    "ModuleEventCreate",
    "ModuleEventResponse",
    "ModuleEventListResponse",
    "LLMConversationCreate",
    "LLMConversationUpdate",
    "LLMConversationResponse",
    "LLMConversationListResponse",
    "LLMMessageCreate",
    "LLMMessageResponse",
    "LLMMessageListResponse",
    "LLMFeedbackCreate",
    "LLMFeedbackResponse",
    "LLMFeedbackListResponse",
    "LLMConversationWithMessagesResponse",
    "ContextRequest",
    "ContextResponse",
]
